spring:
  application:
    name: consumer

  kafka:
    consumer:
      enable-auto-commit: true
      bootstrap-servers: localhost:9092, localhost:9094,localhost:9096
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: payment-created-event
      properties:
        enable:
          idempotence: true

        spring:
          json:
            trusted:
              packages: app.event



server:
  port: 8000
